create table agents (
    id bigint generated by default as identity primary key,
    full_name varchar(160) not null,
    badge_code varchar(60) not null unique,
    cnh_category varchar(20) not null,
    cnh_expiry date not null,
    status varchar(30) not null,
    photo_url varchar(255)
);

create table vehicles (
    id bigint generated by default as identity primary key,
    plate varchar(20) not null unique,
    model varchar(120) not null,
    current_km bigint not null,
    next_maintenance_km bigint not null,
    status varchar(30) not null
);

create table shifts (
    id bigint generated by default as identity primary key,
    agent_id bigint not null,
    agent_name varchar(160) not null,
    vehicle_id bigint not null,
    vehicle_plate varchar(20) not null,
    status varchar(30) not null,
    started_at timestamptz not null,
    scheduled_end_at timestamptz not null
);

create table incidents (
    id bigint generated by default as identity primary key,
    type varchar(40) not null,
    priority varchar(20) not null,
    status varchar(30) not null,
    resident_name varchar(160) not null,
    address varchar(255) not null,
    opened_at timestamptz not null,
    assigned_agent_name varchar(160),
    vehicle_plate varchar(20)
);
