create table residents (
    id bigint generated by default as identity primary key,
    full_name varchar(160) not null,
    phone_number varchar(40) not null,
    address varchar(255) not null,
    reference_note varchar(255),
    status varchar(30) not null
);
