create table shift_telemetry (
    id bigint generated by default as identity primary key,
    shift_id bigint not null unique,
    agent_id bigint not null,
    vehicle_id bigint not null,
    latitude double precision not null,
    longitude double precision not null,
    speed_kmh double precision not null,
    accuracy_meters double precision not null,
    heading_degrees double precision,
    battery_level double precision,
    recorded_at timestamptz not null
);
